[theme]
base="light"
primaryColor = "#1A73E8"           # Azul Google
backgroundColor = "#F5F6FA"        # Cinza claríssimo
secondaryBackgroundColor = "#FFFFFF"
textColor = "#222222"
font = "sans serif"

[general]
email = ""
